import {
  CHECKPOINT_SCHEMA_VERSION,
  mergeCheckpoint,
  normalizeCheckpointText,
  type CheckpointChangedFile,
  type CheckpointContextPolicyState,
  type ContextCheckpoint,
} from "../../context-checkpoints/src/index.ts";
import {
  isToolResultError,
  messageRole,
  messageText,
  toolCalls,
  toolResultName,
} from "./messages.ts";
import type {
  BoundarySelection,
  CompactionPrototypeInput,
  CompactionTranscriptEntry,
} from "./types.ts";

const UNKNOWN_POLICY: CheckpointContextPolicyState = {
  pressure: "unknown",
  measurementSource: "unknown",
  residentTokens: null,
  effectiveWireTokens: null,
  safeLimitTokens: null,
  headroomTokens: null,
  runwayRuns: null,
  capturedAtMs: 0,
  notes: ["Generated by the deterministic Phase 6A fallback."],
};

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function allBoundaryEntries(boundary: BoundarySelection) {
  return [
    ...boundary.history,
    ...boundary.splitTurnPrefix,
    ...boundary.retainedSuffix,
  ];
}

function deriveGoal(entries: readonly CompactionTranscriptEntry[]): string {
  for (const entry of entries) {
    if (messageRole(entry.message) !== "user") continue;
    const text = normalizeCheckpointText(messageText(entry.message));
    if (text)
      return Buffer.from(text, "utf8")
        .subarray(0, 8_000)
        .toString("utf8")
        .replace(/\uFFFD$/u, "");
  }
  return "Continue the task from the retained session suffix.";
}

function deriveFiles(
  entries: readonly CompactionTranscriptEntry[],
): readonly CheckpointChangedFile[] {
  const byPath = new Map<string, CheckpointChangedFile>();
  for (const entry of entries) {
    for (const call of toolCalls(entry.message)) {
      const args = asRecord(call.arguments);
      const path = normalizeCheckpointText(
        typeof args?.path === "string" ? args.path : "",
      );
      if (!path) continue;
      if (call.name === "edit") byPath.set(path, { path, status: "modified" });
      if (call.name === "write") byPath.set(path, { path, status: "created" });
    }
  }
  return [...byPath.values()];
}

function deriveBlockers(
  entries: readonly CompactionTranscriptEntry[],
): readonly string[] {
  const blockers: string[] = [];
  for (const entry of entries) {
    if (!isToolResultError(entry.message)) continue;
    blockers.push(
      `Tool ${toolResultName(entry.message) ?? "result"} reported an error before compaction.`,
    );
  }
  return [...new Set(blockers)];
}

/** Conservative local checkpoint: preserves prior durable state and invents no test/decision claims. */
export function buildDeterministicFallback(options: {
  readonly input: CompactionPrototypeInput;
  readonly boundary: BoundarySelection;
  readonly previousCheckpoint?: ContextCheckpoint;
}): ContextCheckpoint {
  const entries = allBoundaryEntries(options.boundary);
  const currentPolicy = options.input.contextPolicyState ?? UNKNOWN_POLICY;
  if (options.previousCheckpoint) {
    const merged = mergeCheckpoint({
      previous: options.previousCheckpoint,
      updates: {
        workingSet: options.previousCheckpoint.workingSet,
        blockers: options.previousCheckpoint.blockers,
        unresolvedQuestions: options.previousCheckpoint.unresolvedQuestions,
        nextActions:
          options.previousCheckpoint.nextActions.length > 0
            ? options.previousCheckpoint.nextActions
            : [
                `Continue from retained entry ${options.boundary.firstKeptEntryId}.`,
              ],
        changedFiles: deriveFiles(entries),
        criticalReferences: [
          {
            kind: "session-entry",
            id: options.boundary.firstKeptEntryId,
            label: "First entry retained after compaction",
          },
        ],
        contextPolicyState: currentPolicy,
      },
    });
    if (!merged.ok)
      throw new Error(merged.issues.map((issue) => issue.message).join("\n"));
    return merged.checkpoint;
  }

  const candidate: ContextCheckpoint = {
    schemaVersion: CHECKPOINT_SCHEMA_VERSION,
    goal: deriveGoal(entries),
    constraintsAndPreferences: [],
    completedWork: [
      "A deterministic fallback checkpoint was created because model-produced state was unavailable or rejected.",
    ],
    workingSet: [],
    decisions: [],
    changedFiles: deriveFiles(entries),
    testsAndOutcomes: [],
    unresolvedQuestions: [],
    blockers: deriveBlockers(entries),
    nextActions: [
      `Continue from retained entry ${options.boundary.firstKeptEntryId}.`,
    ],
    criticalReferences: [
      {
        kind: "session-entry",
        id: options.boundary.firstKeptEntryId,
        label: "First entry retained after compaction",
      },
    ],
    contextPolicyState: currentPolicy,
  };
  const validation = mergeCheckpoint({ previous: candidate });
  if (!validation.ok)
    throw new Error(validation.issues.map((issue) => issue.message).join("\n"));
  return validation.checkpoint;
}
